name: Based Deploy by Branch - Create Env

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'

      - name: Install dependencies
        run: npm install

      - name: Deploy the branch
        uses: atelier-saulx/based-deploy@main
        with:
          userID: ${{ secrets.BASED_USER_ID }}
          apiKey: ${{ secrets.BASED_API_KEY }}
          size: small
          region: eu-central-1
          action: create-env
